name: birthdaywisher

on:
  schedule:
    - cron: "*/5 * * * *"  
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run test
        run: echo "It works 🎉"
